### ISSUE TITLE
KP on stage1 in OpenWRT mips package

### ISSUE THREAD

**Issue by Vampitech** [FalsePhilosopher/PPPwnWRT#3]
Just FYI. For some reason the stage1.bin provided for MIPS devices is causing Kernel Panic on PS4
As a solution, i've change BIN files in my OpenWRT router with stage1.bin from THeFlow's github and stage2.bin from SISTR0's repo and worked normally.

**Comment by FalsePhilosopher** [comment]
I probably should have looked at the output of the terminal instead of assuming the bin it spit out compiled properly, the 9.00 bin compiled properly and runs no problem but I guess there was an issue with the 11.00 bin. It's been recompiled and pushed, get at me if it doesn't work as I have a 9.00 console and can't test 11.00 consoles.

**Comment by Vampitech** [comment]
I am not the one who posts issues without making sure of things. I try to highlight a problem and at the same time publish what worked for me to correct it while the relevant fixes are made to the repository. That's all.
